spring:
  datasource:
    name: transaction
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/spring_boot_aop?useSSL=FALSE&allowMultiQueries=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
      username: root
      password: '!@#$1234Abcd'
      initialSize: 10
      minIdle: 10
      maxActive: 50
      maxWait: 60000
      time-between-eviction-runs-millis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      useGlobalDataSourceStat: true
  devtools:
    restart:
      enabled: true
      additional-paths: mapper


mybatis:
  mapper-locations: classpath:mapper/*.xml
  cache-enabled: true
  default-statement-timeout: 10000
  map-underscore-to-camel-case: true
  use-generated-keys: true
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl